myList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(myList)
print("Length of the list is:", len(myList))
print("Max value in the list is:", max(myList))
print("Min value in the list is:", min(myList))
print("= " * 30)
print("Sum of all elements in the list is:", sum(myList))
print("Sorted list is:", sorted(myList))
print("Reversed list is:", list(reversed(myList)))
print("^ " * 30)
for item in myList:
    print(item, end=" ")
print("\n" + "= " * 30)
print("Sliced list from index 2 to 5 is:", myList[2:6])
print("Sliced list from index 0 to 5 is:", myList[:6])
print("Sliced list from index 5 to end is:", myList[5:])
print("^ " * 30)
print("Sliced list with step 2 is:", myList[::2])
print("Sliced list from index 1 to 8 with step 3 is:", myList[1:8:3])
print("List after adding 11 and 12:", myList + [11, 12])